name = "Cocoa"
license = "MIT"
licenselink = "https://github.com/nishanths/cocoa-hugo-theme/blob/master/LICENSE.md"
description = "Clear typography and disturbance-free reading"
homepage = "https://github.com/nishanths"
tags = ["proxima-nova", "minimal", "clear"]
features = ["blog", "themes", "responsive", "404"]
min_version = 0.13

[author]
  name = "Subhajit Ghosh"
  homepage = "https://github.com/isubuz"
